### ISSUE TITLE
Genymotion  android4.2  cannot  play youtube video

### ISSUE THREAD

**Issue by ymcao** [JackDinealKIM/youtube-android-player-helper#1]
E/Web Console: Unable to post message to https://www.youtube.com. Recipient has origin http://www.youtube.com.
                                                  at null:0

Viewport argument value "device-width;" for key "width" not recognized. Content ignored. at http://www.youtube.com/:17

**Comment by JackDinealKIM** [comment]
Hello, ymcao.
I checked Genymotion 4.2.2 that perfactly worked.
As well as, AVD Nexus5x it worked very well.
Give me some more detail, I will check it out again.

**Comment by ymcao** [comment]
I  use gennymotion samsung 4.2.2 that cannot play youtube,Otherwise can support fullscreen?,Recently,i research youtube  player for  android,Thanks

**Comment by ymcao** [comment]
i  use  xiaomi   6.0   also  cannot  play  :+1: 

06-07 20:23:47.150 3147-3147/com.whatsmode W/cr_BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 3147
06-07 20:23:51.122 3147-3147/com.whatsmode I/chromium: [INFO:CONSOLE(17)] "The value "device-width;" for key "width" is invalid, and has been ignored.", source: http://www.youtube.com/ (17)
06-07 20:23:51.123 3147-3147/com.whatsmode I/chromium: [INFO:CONSOLE(17)] "The value "1.0;" for key "initial-scale" was truncated to its numeric prefix.", source: http://www.youtube.com/ (17)
06-07 20:23:51.123 3147-3147/com.whatsmode I/chromium: [INFO:CONSOLE(17)] "The value "1.0;" for key "maximum-scale" was truncated to its numeric prefix.", source: http://www.youtube.com/ (17)
06-07 20:23:51.123 3147-3147/com.whatsmode I/chromium: [INFO:CONSOLE(17)] "The value "0;" for key "user-scalable" was truncated to its numeric prefix.", source: http://www.youtube.com/ (17)
06-07 20:23:51.123 3147-3147/com.whatsmode I/chromium: [INFO:CONSOLE(17)] "Error parsing a meta element's content: ';' is not a valid key-value pair separator. Please use ',' instead.", source: http://www.youtube.com/ (17)
06-07 20:23:53.243 3147-3147/com.whatsmode I/chromium: [INFO:CONSOLE(0)] "Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('http://www.youtube.com').", source:  (0)

**Comment by JackDinealKIM** [comment]
My gennymotion is still working on it.
So I recommend that you add below code in manifest.xml
- add this code at application tag.
  android:hardwareAccelerated="true"

Additionally, let me check out Fullscreen function.

**Comment by ymcao** [comment]
Thanks
