### ISSUE TITLE
Android 4.1.2 not working

### ISSUE THREAD

**Issue by josealonsogarcia** [JackDinealKIM/youtube-android-player-helper#3]
Hi,

Testing in Android 4.1.2 seems not working, only the audio is loaded but the image don't.  Is there a minimum Android version to work?

Thanks for your work

**Comment by JackDinealKIM** [comment]
Hi,  this project is minSdkVersion 11.
So, that you asked 4.1.2 is able to work properly but sometimes some manufacturer occur problems. I think hardware accelator.

I recommend that you add hardware option in Manifest.xml

something like this.
add this code at application tag. android:hardwareAccelerated="true"

I wish. It will help for you.

**Comment by josealonsogarcia** [comment]
Hi, yes i've added the android:hardwareAccelerated="true" ..., maybe is a manufacturer problem. 

If helps, i m testing on a Motorola XOOM tablet (with Android 4.1.2). In nexus 4 with Android 5.1.1 works without problem.

Thanks!
