### ISSUE TITLE
Google Policy

### ISSUE THREAD

**Issue by cdelon** [JackDinealKIM/youtube-android-player-helper#6]
Impossible to publish new app because it violates their device and network abuse policy and section 4.4 of their Developer Distribution Agreement.

Now, you can't pllay youtube video in background without using Youtube API

Any solution ?

**Comment by spiralni** [comment]
If true, then this helper is done! d*mn google

**Comment by JackDinealKIM** [comment]
You have to call on destory.
like this, or onPause.

 @Override
    protected void onDestroy() {
        super.onDestroy();
        // this is optional but you need.
        youtubePlayerView.destroy();
    }

onPause() {
youtubePlayerView.pause();
}
