### ISSUE TITLE
Video not playing automatically

### ISSUE THREAD

**Issue by chintandesai49** [JackDinealKIM/youtube-android-player-helper#7]
On devices below Android 5, Lollipop video doesn't start automatically.
I have used .play() method i onReady() method.
And I'm getting following error:
**A WebView method was called on a thread 'JavaBridge'. All WebView methods must be called on the same thread**
which could easily solved by method runOnUiThread method.

**Comment by S26T** [comment]
Hi. Just perform a task in the main thread.

`getActivity().runOnUiThread(new Runnable() {
                    @Override
                    public void run() {
                        youtubePlayerView.play();
                    }
                });`

**Comment by chintandesai49** [comment]
Thanks it worked.
