### ISSUE TITLE
Auto play not work 

### ISSUE THREAD

**Issue by MinThantZinHtun** [JackDinealKIM/youtube-android-player-helper#8]
I  write
 setautoplay(1) 
to Ytparam  but video not auto play  

![issues](https://cloud.githubusercontent.com/assets/25447958/23196960/530d4e3e-f8eb-11e6-89c8-ecb9e699e097.PNG)

**Comment by JackDinealKIM** [comment]
This is mobile device issues.  I can't fix it.
